"""initial schema

Revision ID: 28dbb5258b3a
Revises: d3aec2bc7205
Create Date: 2026-05-29 20:22:28.835692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dbb5258b3a'
down_revision: Union[str, Sequence[str], None] = 'd3aec2bc7205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_jobs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intent_jobs', 'description')
    # ### end Alembic commands ###
