"""initial schema

Revision ID: cf947485bfa8
Revises: 28dbb5258b3a
Create Date: 2026-05-29 20:23:57.448144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf947485bfa8'
down_revision: Union[str, Sequence[str], None] = '28dbb5258b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intent_jobs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
