"""initial schema

Revision ID: d3aec2bc7205
Revises: 
Create Date: 2026-05-29 20:18:13.883449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3aec2bc7205'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_urls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('global_crawl_status', sa.Enum('pending', 'queued', 'crawling', 'completed', 'failed', 'blocked', 'timeout', name='crawl_status'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url')
    )
    op.create_index('idx_canonical_crawl_status', 'canonical_urls', ['global_crawl_status'], unique=False)
    op.create_index('idx_canonical_domain', 'canonical_urls', ['domain'], unique=False)
    op.create_table('intent_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('request_name', sa.Text(), nullable=False),
    sa.Column('original_query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'completed', 'failed', name='job_status'), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_company_size', sa.Integer(), nullable=True),
    sa.Column('max_company_size', sa.Integer(), nullable=True),
    sa.Column('target_personas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('buying_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('negative_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_priority_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_expression', sa.Text(), nullable=False),
    sa.Column('lead_score_threshold', sa.Integer(), nullable=False),
    sa.Column('max_urls_per_run', sa.Integer(), nullable=False),
    sa.Column('total_seed_urls', sa.Integer(), nullable=False),
    sa.Column('total_discovered_urls', sa.Integer(), nullable=False),
    sa.Column('total_processed_urls', sa.Integer(), nullable=False),
    sa.Column('total_qualified_leads', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intent_jobs_created_by', 'intent_jobs', ['created_by'], unique=False)
    op.create_index('idx_intent_jobs_next_run', 'intent_jobs', ['next_run_at'], unique=False)
    op.create_index('idx_intent_jobs_status', 'intent_jobs', ['status'], unique=False)
    op.create_index('idx_intent_jobs_tenant', 'intent_jobs', ['tenant_id'], unique=False)
    op.create_table('crawled_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_url_id', sa.UUID(), nullable=False),
    sa.Column('crawl_provider', sa.Enum('scraperapi', 'playwright', 'axios', 'zenrows', 'firecrawl', 'manual', name='crawl_provider'), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('crawl_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('crawler_version', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawled_pages_crawled_at', 'crawled_pages', ['crawled_at'], unique=False)
    op.create_index('idx_crawled_pages_provider', 'crawled_pages', ['crawl_provider'], unique=False)
    op.create_index('idx_crawled_pages_url', 'crawled_pages', ['canonical_url_id'], unique=False)
    op.create_table('generated_intents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('intent_job_id', sa.UUID(), nullable=False),
    sa.Column('intent_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intent_job_id'], ['intent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_intents_job', 'generated_intents', ['intent_job_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('generated_intent_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='query_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_intent_id'], ['generated_intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_queries_status', 'search_queries', ['status'], unique=False)
    op.create_table('discovered_urls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('canonical_url_id', sa.UUID(), nullable=False),
    sa.Column('search_query_id', sa.UUID(), nullable=False),
    sa.Column('source_engine', sa.String(length=50), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('discovery_depth', sa.Integer(), nullable=False),
    sa.Column('crawl_status', sa.Enum('pending', 'queued', 'crawling', 'completed', 'failed', 'blocked', 'timeout', name='crawl_status'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_url_id'], ['canonical_urls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_discovered_canonical', 'discovered_urls', ['canonical_url_id'], unique=False)
    op.create_index('idx_discovered_crawl_status', 'discovered_urls', ['crawl_status'], unique=False)
    op.create_index('idx_discovered_tenant', 'discovered_urls', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_discovered_tenant', table_name='discovered_urls')
    op.drop_index('idx_discovered_crawl_status', table_name='discovered_urls')
    op.drop_index('idx_discovered_canonical', table_name='discovered_urls')
    op.drop_table('discovered_urls')
    op.drop_index('idx_search_queries_status', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index('idx_generated_intents_job', table_name='generated_intents')
    op.drop_table('generated_intents')
    op.drop_index('idx_crawled_pages_url', table_name='crawled_pages')
    op.drop_index('idx_crawled_pages_provider', table_name='crawled_pages')
    op.drop_index('idx_crawled_pages_crawled_at', table_name='crawled_pages')
    op.drop_table('crawled_pages')
    op.drop_index('idx_intent_jobs_tenant', table_name='intent_jobs')
    op.drop_index('idx_intent_jobs_status', table_name='intent_jobs')
    op.drop_index('idx_intent_jobs_next_run', table_name='intent_jobs')
    op.drop_index('idx_intent_jobs_created_by', table_name='intent_jobs')
    op.drop_table('intent_jobs')
    op.drop_index('idx_canonical_domain', table_name='canonical_urls')
    op.drop_index('idx_canonical_crawl_status', table_name='canonical_urls')
    op.drop_table('canonical_urls')
    # ### end Alembic commands ###
